# Generated by Django 6.0.4 on 2026-04-22 15:47

import django.db.models.deletion
import dokumen.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_akreditasi', '0003_importlog_importlogitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_pemilik', models.CharField(help_text='UNIVERSITAS / BIRO / FAKULTAS / PRODI', max_length=15, verbose_name='Kategori Pemilik')),
                ('scope_kode_prodi', models.CharField(blank=True, help_text='Diisi kalau kategori = PRODI', max_length=10, verbose_name='Kode Prodi')),
                ('scope_kode_fakultas', models.CharField(blank=True, help_text='Diisi kalau kategori = FAKULTAS atau PRODI', max_length=10, verbose_name='Kode Fakultas')),
                ('scope_kode_unit_kerja', models.CharField(blank=True, help_text='Diisi kalau kategori = BIRO', max_length=20, verbose_name='Kode Unit Kerja (Biro/Lembaga)')),
                ('judul', models.CharField(help_text='Judul yang akan tampil ke user. Default: nama dokumen dari butir.', max_length=300, verbose_name='Judul Dokumen')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi / Catatan')),
                ('status_akses', models.CharField(choices=[('TERBUKA', 'Terbuka (Publik)'), ('INTERNAL', 'Internal (Perlu Login)')], default='INTERNAL', max_length=10, verbose_name='Status Akses')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final / Dipublikasikan'), ('ARSIP', 'Diarsipkan')], default='FINAL', max_length=10, verbose_name='Status Dokumen')),
                ('tahun_akademik', models.CharField(blank=True, help_text='Contoh: 2024/2025', max_length=20, verbose_name='Tahun Akademik')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Lihat')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Download')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
                ('butir_dokumen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dokumen_terunggah', to='master_akreditasi.butirdokumen', verbose_name='Butir Dokumen')),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dokumen_diupdate', to=settings.AUTH_USER_MODEL, verbose_name='Terakhir Diupdate Oleh')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dokumen_diupload', to=settings.AUTH_USER_MODEL, verbose_name='Pengupload Pertama')),
            ],
            options={
                'verbose_name': 'Dokumen Akreditasi',
                'verbose_name_plural': 'Dokumen Akreditasi',
                'db_table': 'dokumen',
                'ordering': ['-tanggal_diubah'],
            },
        ),
        migrations.CreateModel(
            name='DokumenRevisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_revisi', models.PositiveIntegerField(verbose_name='Nomor Revisi')),
                ('file', models.FileField(max_length=500, upload_to=dokumen.models.dokumen_upload_path, verbose_name='File')),
                ('original_filename', models.CharField(max_length=300, verbose_name='Nama File Asli')),
                ('file_size_kb', models.PositiveIntegerField(default=0, verbose_name='Ukuran (KB)')),
                ('file_hash', models.CharField(blank=True, help_text='Hash untuk verifikasi integrity', max_length=64, verbose_name='SHA-256 Hash')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME Type')),
                ('extension', models.CharField(blank=True, max_length=10, verbose_name='Ekstensi')),
                ('catatan_revisi', models.TextField(blank=True, help_text='Kenapa di-update? Perubahan apa?', verbose_name='Catatan Revisi')),
                ('aktif', models.BooleanField(default=True, help_text='Hanya 1 revisi yang aktif per dokumen', verbose_name='Aktif')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('dokumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisi', to='dokumen.dokumen')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisi_diupload', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revisi Dokumen',
                'verbose_name_plural': 'Revisi Dokumen',
                'db_table': 'dokumen_revisi',
                'ordering': ['-nomor_revisi'],
            },
        ),
        migrations.CreateModel(
            name='DokumenAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(choices=[('VIEW', 'Lihat Inline'), ('DOWNLOAD', 'Download'), ('UPLOAD', 'Upload / Create'), ('REVISI', 'Upload Revisi'), ('DELETE', 'Hapus'), ('EDIT_META', 'Edit Metadata')], max_length=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.CharField(blank=True, max_length=200)),
                ('dokumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='dokumen.dokumen')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumen_access_logs', to=settings.AUTH_USER_MODEL)),
                ('revisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='dokumen.dokumenrevisi')),
            ],
            options={
                'verbose_name': 'Log Akses Dokumen',
                'verbose_name_plural': 'Log Akses Dokumen',
                'db_table': 'dokumen_access_log',
                'ordering': ['-waktu'],
            },
        ),
        migrations.AddConstraint(
            model_name='dokumenrevisi',
            constraint=models.UniqueConstraint(fields=('dokumen', 'nomor_revisi'), name='unique_dokumen_revisi_nomor'),
        ),
    ]
