# Generated by Django 6.0.4 on 2026-04-22 16:57

import dokumen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumenrevisi',
            name='gdrive_file_id',
            field=models.CharField(blank=True, help_text='Extracted dari URL untuk embed preview', max_length=100, verbose_name='Google Drive File ID'),
        ),
        migrations.AddField(
            model_name='dokumenrevisi',
            name='gdrive_url',
            field=models.URLField(blank=True, help_text='Diisi kalau storage_type=GDRIVE', max_length=500, verbose_name='Google Drive URL'),
        ),
        migrations.AddField(
            model_name='dokumenrevisi',
            name='is_link_broken',
            field=models.BooleanField(default=False, help_text='Flag kalau link GDrive tidak accessible', verbose_name='Link Broken?'),
        ),
        migrations.AddField(
            model_name='dokumenrevisi',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terakhir Diverifikasi'),
        ),
        migrations.AddField(
            model_name='dokumenrevisi',
            name='storage_type',
            field=models.CharField(choices=[('LOCAL', 'Upload File Lokal'), ('GDRIVE', 'Google Drive Link')], default='LOCAL', max_length=10, verbose_name='Tipe Storage'),
        ),
        migrations.AlterField(
            model_name='dokumenrevisi',
            name='file',
            field=models.FileField(blank=True, help_text='Diisi kalau storage_type=LOCAL', max_length=500, null=True, upload_to=dokumen.models.dokumen_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='dokumenrevisi',
            name='original_filename',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nama File Asli'),
        ),
    ]
