# Generated by Django 6.0.4 on 2026-04-23 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0002_dokumenrevisi_gdrive_file_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifikasiDokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Review'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('NEED_REVISION', 'Perlu Revisi')], db_index=True, default='PENDING', max_length=20, verbose_name='Status Verifikasi')),
                ('catatan', models.TextField(blank=True, default='', help_text='Disarankan diisi untuk REJECTED/NEED_REVISION agar uploader tau harus fix apa.', verbose_name='Catatan Verifikator')),
                ('tanggal_verifikasi', models.DateTimeField(blank=True, help_text='Diisi otomatis saat status berubah dari PENDING.', null=True, verbose_name='Tanggal Verifikasi')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('tanggal_diubah', models.DateTimeField(auto_now=True, verbose_name='Diubah Pada')),
                ('revisi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verifikasi', to='dokumen.dokumenrevisi', verbose_name='Revisi Dokumen')),
                ('verifikator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifikasi_dilakukan', to=settings.AUTH_USER_MODEL, verbose_name='Diverifikasi Oleh')),
            ],
            options={
                'verbose_name': 'Verifikasi Dokumen',
                'verbose_name_plural': 'Verifikasi Dokumen',
                'db_table': 'verifikasi_dokumen',
                'ordering': ['-tanggal_dibuat'],
            },
        ),
        migrations.CreateModel(
            name='VerifikasiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(help_text='APPROVED, REJECTED, NEED_REVISION, RESET', max_length=20)),
                ('status_lama', models.CharField(blank=True, max_length=20)),
                ('status_baru', models.CharField(max_length=20)),
                ('catatan', models.TextField(blank=True, default='')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('dilakukan_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifikasi_log', to=settings.AUTH_USER_MODEL)),
                ('verifikasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dokumen.verifikasidokumen')),
            ],
            options={
                'verbose_name': 'Log Verifikasi',
                'verbose_name_plural': 'Log Verifikasi',
                'db_table': 'verifikasi_dokumen_log',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.AddIndex(
            model_name='verifikasidokumen',
            index=models.Index(fields=['status', '-tanggal_dibuat'], name='verifikasi__status_ff8aee_idx'),
        ),
    ]
