# Generated by Django 6.0.4 on 2026-04-26 15:15
# MODIFIED: split AddField public_token into 3 steps to handle unique
# constraint for existing rows (RunPython generates unique UUID per row).

import uuid
from django.db import migrations, models


def generate_unique_tokens(apps, schema_editor):
    """
    Generate UUID unik untuk setiap dokumen existing.
    Dipanggil oleh RunPython di tahap 2.
    """
    Dokumen = apps.get_model('dokumen', 'Dokumen')
    for dok in Dokumen.objects.all():
        dok.public_token = uuid.uuid4()
        dok.save(update_fields=['public_token'])


def reverse_tokens(apps, schema_editor):
    """No-op untuk reverse — saat rollback, field akan di-drop oleh AlterField/RemoveField."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0003_verifikasidokumen_verifikasilog_and_more'),
    ]

    operations = [
        # === public_enabled (sederhana, default True) ===
        migrations.AddField(
            model_name='dokumen',
            name='public_enabled',
            field=models.BooleanField(
                default=True,
                help_text='Centang agar dokumen ini dapat diakses via link public. Link tetap hanya aktif jika status=FINAL.',
                verbose_name='Public Link Aktif',
            ),
        ),

        # === public_token: tahap 1 — tambah field tanpa unique, nullable ===
        migrations.AddField(
            model_name='dokumen',
            name='public_token',
            field=models.UUIDField(
                null=True,
                editable=False,
                help_text='Token UUID untuk akses public via hyperlink LED',
                verbose_name='Token Public Link',
            ),
        ),

        # === public_token: tahap 2 — generate UUID unik per row existing ===
        migrations.RunPython(
            generate_unique_tokens,
            reverse_code=reverse_tokens,
        ),

        # === public_token: tahap 3 — aktifkan unique constraint + default ===
        migrations.AlterField(
            model_name='dokumen',
            name='public_token',
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text='Token UUID untuk akses public via hyperlink LED',
                unique=True,
                verbose_name='Token Public Link',
            ),
        ),

        # === update choices di AksiType DokumenAccessLog ===
        migrations.AlterField(
            model_name='dokumenaccesslog',
            name='aksi',
            field=models.CharField(
                choices=[
                    ('VIEW', 'Lihat Inline'),
                    ('DOWNLOAD', 'Download'),
                    ('UPLOAD', 'Upload / Create'),
                    ('REVISI', 'Upload Revisi'),
                    ('DELETE', 'Hapus'),
                    ('EDIT_META', 'Edit Metadata'),
                    ('PUBLIC_VIEW', 'Public View (via link LED)'),
                    ('PUBLIC_DOWNLOAD', 'Public Download (via link LED)'),
                ],
                max_length=15,
            ),
        ),
    ]