# Generated by Django 6.0.4 on 2026-10-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0004_dokumen_public_enabled_dokumen_public_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenrevisi',
            name='gdrive_url',
            field=models.URLField(blank=True, help_text='Diisi kalau storage_type=GDRIVE, atau URL aplikasi kalau storage_type=LINK', max_length=500, verbose_name='Google Drive URL'),
        ),
        migrations.AlterField(
            model_name='dokumenrevisi',
            name='storage_type',
            field=models.CharField(choices=[('LOCAL', 'Upload File Lokal'), ('GDRIVE', 'Google Drive Link'), ('LINK', 'Tautan Aplikasi/Website')], default='LOCAL', max_length=10, verbose_name='Tipe Storage'),
        ),
    ]
