# Generated by Django 6.0.4 on 2026-10-11 04:37

from django.db import migrations, models


def isi_jenis(apps, schema_editor):
    """Tebak jenis dokumen untuk data lama (judul -> nama butir; revisi LINK -> APLIKASI)."""
    from dokumen.pustaka import tebak_jenis

    Dokumen = apps.get_model("dokumen", "Dokumen")
    DokumenRevisi = apps.get_model("dokumen", "DokumenRevisi")
    link_ids = set(
        DokumenRevisi.objects.filter(aktif=True, storage_type="LINK").values_list("dokumen_id", flat=True)
    )
    for d in Dokumen.objects.filter(jenis_dokumen="").select_related("butir_dokumen").iterator():
        jenis = tebak_jenis(d.judul, d.butir_dokumen.nama_dokumen, d.pk in link_ids)
        Dokumen.objects.filter(pk=d.pk).update(jenis_dokumen=jenis)


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0005_revisi_storage_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='jenis_dokumen',
            field=models.CharField(blank=True, choices=[('KEBIJAKAN', 'Kebijakan / Peraturan'), ('PEDOMAN', 'Pedoman / Manual / Standar'), ('SK', 'Surat Keputusan (SK)'), ('RENCANA', 'Renstra / Renop / Rencana'), ('SOP', 'SOP / Prosedur'), ('LAPORAN', 'Laporan / Evaluasi / Bukti'), ('FORMULIR', 'Formulir / Instrumen'), ('APLIKASI', 'Tautan Aplikasi / Website'), ('LAINNYA', 'Lainnya')], db_index=True, help_text='Pengelompokan di Pustaka Dokumen. Kosongkan agar ditebak otomatis dari judul.', max_length=12, verbose_name='Jenis Dokumen'),
        ),
        migrations.RunPython(isi_jenis, migrations.RunPython.noop),
    ]
