# Generated by Django 6.0.4 on 2026-10-11 04:37

from django.db import migrations, models


def isi_jenis(apps, schema_editor):
    """Dulu: tebak jenis untuk data lama. Field ini digantikan kategori (0007), yang
    menebak ulang dari judul; jadi di sini cukup no-op agar migrasi tidak bergantung kode lama."""
    return


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0005_revisi_storage_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='jenis_dokumen',
            field=models.CharField(blank=True, choices=[('KEBIJAKAN', 'Kebijakan / Peraturan'), ('PEDOMAN', 'Pedoman / Manual / Standar'), ('SK', 'Surat Keputusan (SK)'), ('RENCANA', 'Renstra / Renop / Rencana'), ('SOP', 'SOP / Prosedur'), ('LAPORAN', 'Laporan / Evaluasi / Bukti'), ('FORMULIR', 'Formulir / Instrumen'), ('APLIKASI', 'Tautan Aplikasi / Website'), ('LAINNYA', 'Lainnya')], db_index=True, help_text='Pengelompokan di Pustaka Dokumen. Kosongkan agar ditebak otomatis dari judul.', max_length=12, verbose_name='Jenis Dokumen'),
        ),
        migrations.RunPython(isi_jenis, migrations.RunPython.noop),
    ]
