# Generated by Django 6.0.4 on 2026-10-11 04:58

import re

import django.db.models.deletion
from django.db import migrations, models

# (urutan, kode, nama, kata kunci)
KATEGORI_AWAL = [
    (10, "peraturan-perundangan", "Peraturan Perundang-undangan",
     "undang-undang, undang undang, uu no, uu nomor, peraturan pemerintah, pp no, pp nomor, peraturan presiden, perpres, "
     "permendikbud, permendikbudristek, permenristekdikti, permendiktisaintek, peraturan menteri, permen, kepmen, "
     "keputusan menteri, kepmendikbudristek, peraturan ban-pt, peraturan ban pt, peraturan lam"),
    (20, "kebijakan-pemerintah", "Kebijakan Pemerintah / Kementerian",
     "surat edaran, se dirjen, kebijakan pemerintah, kebijakan kementerian, pedoman kementerian, panduan kementerian, "
     "dirjen, kemendikbud, kemendikbudristek, kemdikbud, kemdiktisaintek, ban-pt, lldikti, lam ptkes, lamspak"),
    (30, "statuta", "Statuta", "statuta"),
    (40, "peraturan-rektor", "Peraturan Rektor", "peraturan rektor, perrek, peraturan universitas"),
    (50, "sk-rektor", "SK Rektor", "sk rektor, keputusan rektor, surat keputusan rektor"),
    (60, "sk-yayasan", "SK Yayasan", "sk yayasan, keputusan yayasan, keputusan ketua yayasan, keputusan pembina"),
    (70, "sk-dekan", "SK Dekan", "sk dekan, keputusan dekan, surat keputusan dekan"),
    (80, "sk-lainnya", "SK Lainnya", "sk, surat keputusan, keputusan, surat tugas"),
    (90, "kebijakan-internal", "Kebijakan Internal", "kebijakan, kebijakan spmi, kode etik, peraturan, tata kelola, tata pamong"),
    (100, "pedoman", "Pedoman / Manual", "pedoman, manual, panduan, buku saku, petunjuk, juknis, juklak, buku pedoman"),
    (110, "standar", "Standar", "standar, standar spmi, standar mutu, standar pendidikan, standar penelitian, standar pkm"),
    (120, "sop", "SOP / Prosedur", "sop, prosedur, standar operasional, standar operasional prosedur, alur, mekanisme"),
    (130, "rencana", "Renstra / Renop / Rencana",
     "renstra, renop, rencana strategis, rencana operasional, rencana induk, rip, roadmap, road map, peta jalan, "
     "rkat, rencana kerja, rencana anggaran, rencana"),
    (140, "laporan", "Laporan / Evaluasi",
     "laporan, evaluasi, audit, ami, rtm, tinjauan manajemen, survei, survey, notulen, rekap, rekapitulasi, "
     "analisis, hasil, bukti, lkps, led, monev"),
    (150, "mou-kerja-sama", "MoU / Kerja Sama",
     "mou, moa, memorandum, nota kesepahaman, perjanjian kerja sama, perjanjian kerjasama, kerja sama, kerjasama, pks"),
    (160, "formulir", "Formulir / Instrumen", "formulir, form, borang, template, kuesioner, instrumen"),
    (170, "aplikasi", "Tautan Aplikasi / Website", ""),
    (999, "lainnya", "Lainnya", ""),
]

# Fallback dari jenis_dokumen lama (0006) bila judul tidak cocok kata kunci mana pun
JENIS_LAMA = {
    "KEBIJAKAN": "kebijakan-internal", "PEDOMAN": "pedoman", "SK": "sk-lainnya", "RENCANA": "rencana",
    "SOP": "sop", "LAPORAN": "laporan", "FORMULIR": "formulir", "APLIKASI": "aplikasi", "LAINNYA": "lainnya",
}


def _normal(t):
    return " ".join(re.sub(r"[^a-z0-9]+", " ", (t or "").lower()).split())


def _cocok(teks, aturan):
    t = f" {_normal(teks)} "
    best = None
    for kode, urutan, kunci in aturan:
        for kw in kunci:
            pos = t.find(f" {kw} ") if kw else -1
            if pos >= 0:
                skor = (-pos, len(kw), -urutan)
                if best is None or skor > best[0]:
                    best = (skor, kode)
    return best[1] if best else None


def isi_kategori(apps, schema_editor):
    Kategori = apps.get_model("dokumen", "KategoriDokumen")
    Dokumen = apps.get_model("dokumen", "Dokumen")
    Revisi = apps.get_model("dokumen", "DokumenRevisi")
    per_kode = {}
    for urutan, kode, nama, kunci in KATEGORI_AWAL:
        per_kode[kode], _ = Kategori.objects.get_or_create(
            kode=kode, defaults={"nama": nama, "kata_kunci": kunci, "urutan": urutan})
    aturan = [(kode, urutan, [_normal(k) for k in kunci.split(",") if k.strip()])
              for urutan, kode, _n, kunci in KATEGORI_AWAL if kunci]
    link_ids = set(Revisi.objects.filter(aktif=True, storage_type="LINK").values_list("dokumen_id", flat=True))
    for d in Dokumen.objects.select_related("butir_dokumen").iterator():
        if d.pk in link_ids:
            kode = "aplikasi"
        else:
            kode = (_cocok(d.judul, aturan)
                    or (_cocok(d.butir_dokumen.nama_dokumen, aturan) if d.butir_dokumen_id else None)
                    or JENIS_LAMA.get(d.jenis_dokumen or "", "lainnya"))
        Dokumen.objects.filter(pk=d.pk).update(kategori=per_kode[kode])


def kembalikan_jenis(apps, schema_editor):
    Dokumen = apps.get_model("dokumen", "Dokumen")
    balik = {"aplikasi": "APLIKASI", "pedoman": "PEDOMAN", "standar": "PEDOMAN", "sop": "SOP", "rencana": "RENCANA",
             "laporan": "LAPORAN", "formulir": "FORMULIR", "sk-rektor": "SK", "sk-yayasan": "SK", "sk-dekan": "SK",
             "sk-lainnya": "SK"}
    for d in Dokumen.objects.select_related("kategori").iterator():
        kode = d.kategori.kode if d.kategori_id else ""
        jenis = balik.get(kode, "KEBIJAKAN" if kode in ("peraturan-perundangan", "kebijakan-pemerintah", "statuta",
                                                         "peraturan-rektor", "kebijakan-internal") else "LAINNYA")
        Dokumen.objects.filter(pk=d.pk).update(jenis_dokumen=jenis)



class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0006_jenis_dokumen'),
        ('master_akreditasi', '0009_sinkron_jenis_vmts'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriDokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=120, unique=True, verbose_name='Nama Kategori')),
                ('kode', models.SlugField(help_text='Huruf kecil & tanda hubung, mis. sk-rektor', max_length=60, unique=True, verbose_name='Kode')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('kata_kunci', models.TextField(blank=True, help_text='Pisahkan dengan koma. Judul dokumen yang memuat kata ini otomatis masuk kategori ini (kata yang muncul paling awal di judul menang, lalu yang terpanjang). Contoh: sk rektor, keputusan rektor', verbose_name='Kata Kunci Tebakan')),
                ('urutan', models.PositiveIntegerField(default=100, verbose_name='Urutan')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategori Dokumen',
                'verbose_name_plural': 'Kategori Dokumen',
                'db_table': 'kategori_dokumen',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.AddField(
            model_name='dokumen',
            name='nomor_dokumen',
            field=models.CharField(blank=True, help_text='Contoh: 123/UNISAN/SK/IV/2024', max_length=150, verbose_name='Nomor Dokumen'),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='penerbit',
            field=models.CharField(blank=True, help_text='Contoh: Rektor UNISAN, Yayasan, Kemendikbudristek', max_length=200, verbose_name='Penerbit / Penetap'),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='tanggal_dokumen',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Penetapan'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='butir_dokumen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dokumen_terunggah', to='master_akreditasi.butirdokumen', verbose_name='Butir Dokumen'),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='kategori',
            field=models.ForeignKey(blank=True, help_text='Kosongkan agar ditebak otomatis dari judul (kata kunci kategori).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dokumen', to='dokumen.kategoridokumen', verbose_name='Kategori Dokumen'),
        ),
        migrations.RunPython(isi_kategori, kembalikan_jenis),
        migrations.RemoveField(
            model_name='dokumen',
            name='jenis_dokumen',
        ),
    ]
