# Generated by Django 6.0.4 on 2026-10-11 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0007_kategori_dokumen'),
        ('master_akreditasi', '0009_sinkron_jenis_vmts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumenTautanButir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_kode_prodi', models.CharField(blank=True, max_length=10, verbose_name='Berlaku untuk Prodi')),
                ('scope_kode_fakultas', models.CharField(blank=True, max_length=10, verbose_name='Berlaku untuk Fakultas')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('butir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tautan_dokumen', to='master_akreditasi.butirdokumen', verbose_name='Butir')),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ditautkan oleh')),
                ('dokumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tautan_butir', to='dokumen.dokumen', verbose_name='Dokumen')),
            ],
            options={
                'verbose_name': 'Tautan Dokumen ke Butir',
                'verbose_name_plural': 'Tautan Dokumen ke Butir',
                'db_table': 'dokumen_tautan_butir',
                'ordering': ['-tanggal_dibuat'],
                'constraints': [models.UniqueConstraint(fields=('dokumen', 'butir', 'scope_kode_prodi', 'scope_kode_fakultas'), name='uniq_tautan_dokumen_butir_cakupan')],
            },
        ),
    ]
