# Generated by Django 6.0.4 on 2026-04-22 12:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nidn', models.CharField(blank=True, help_text='Nomor Induk Dosen Nasional (untuk dosen)', max_length=20, null=True, verbose_name='NIDN')),
                ('nip', models.CharField(blank=True, help_text='Nomor Induk Pegawai (untuk tendik)', max_length=30, null=True, verbose_name='NIP')),
                ('no_telepon', models.CharField(blank=True, max_length=20, null=True, verbose_name='No. Telepon')),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='users/foto/', verbose_name='Foto Profil')),
                ('data_dosen_id', models.BigIntegerField(blank=True, help_text='Link ke master.data_dosen.id di SIMDA', null=True, verbose_name='ID Dosen SIMDA')),
                ('data_tendik_id', models.BigIntegerField(blank=True, help_text='Link ke master.data_tendik.id di SIMDA', null=True, verbose_name='ID Tendik SIMDA')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Pengguna',
                'verbose_name_plural': 'Pengguna',
                'db_table': 'user',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ScopeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin Pustikom'), ('PIMP_REKTORAT', 'Pimpinan Rektorat'), ('LPM', 'LPM / GKM (Validator Mutu)'), ('OP_UNIVERSITAS', 'Operator Universitas'), ('PIMP_BIRO', 'Pimpinan Biro/Lembaga'), ('OP_BIRO', 'Operator Biro/Lembaga'), ('PIMP_FAKULTAS', 'Pimpinan Fakultas'), ('OP_FAKULTAS', 'Operator Fakultas'), ('PIMP_PRODI', 'Pimpinan Prodi'), ('OP_PRODI', 'Operator Prodi'), ('ASESOR', 'Asesor Eksternal')], max_length=30, verbose_name='Role')),
                ('level', models.CharField(choices=[('UNIVERSITAS', 'Universitas'), ('BIRO', 'Biro / Lembaga'), ('FAKULTAS', 'Fakultas'), ('PRODI', 'Program Studi')], max_length=20, verbose_name='Level Organisasi')),
                ('unit_kerja_id', models.BigIntegerField(blank=True, help_text='Link ke master.unit_kerja.id (jika level=BIRO)', null=True, verbose_name='ID Unit Kerja (Biro/Lembaga)')),
                ('fakultas_id', models.BigIntegerField(blank=True, help_text='Link ke master.fakultas.id (jika level=FAKULTAS atau PRODI)', null=True, verbose_name='ID Fakultas')),
                ('prodi_id', models.BigIntegerField(blank=True, help_text='Link ke master.program_studi.id (jika level=PRODI)', null=True, verbose_name='ID Program Studi')),
                ('is_pimpinan', models.BooleanField(default=False, help_text='True untuk pimpinan, False untuk operator', verbose_name='Pimpinan?')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('tanggal_mulai', models.DateField(auto_now_add=True, verbose_name='Tanggal Mulai Berlaku')),
                ('tanggal_berakhir', models.DateField(blank=True, help_text='Kosongkan jika tidak ada batas (terutama untuk Asesor)', null=True, verbose_name='Tanggal Berakhir')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scope_dibuat', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Scope Pengguna',
                'verbose_name_plural': 'Scope Pengguna',
                'db_table': 'scope_user',
                'ordering': ['user__username', 'role'],
                'constraints': [models.UniqueConstraint(fields=('user', 'role', 'unit_kerja_id', 'fakultas_id', 'prodi_id'), name='unique_user_role_unit')],
            },
        ),
    ]
