# Generated by Django 6.0.4 on 2026-04-22 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(help_text='Hash dari user-agent + IP prefix', max_length=64, verbose_name='Device Fingerprint')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('browser_name', models.CharField(blank=True, max_length=50, verbose_name='Browser')),
                ('os_name', models.CharField(blank=True, max_length=50, verbose_name='OS')),
                ('device_type', models.CharField(blank=True, help_text='Desktop / Mobile / Tablet', max_length=20, verbose_name='Tipe Device')),
                ('is_trusted', models.BooleanField(default=False, help_text='User telah mengkonfirmasi device ini dipercaya', verbose_name='Dipercaya')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Pertama Login')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Login Terakhir')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Terakhir')),
                ('aktif', models.BooleanField(default=True, verbose_name='Sesi Aktif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Session',
                'verbose_name_plural': 'Device Sessions',
                'db_table': 'device_session',
                'ordering': ['-last_seen'],
                'constraints': [models.UniqueConstraint(fields=('user', 'device_fingerprint'), name='unique_user_device')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(max_length=200, verbose_name='Username/Email Dicoba')),
                ('status', models.CharField(choices=[('SUCCESS', 'Berhasil'), ('FAILED_PASSWORD', 'Password Salah'), ('FAILED_USERNAME', 'Username Tidak Ditemukan'), ('FAILED_INACTIVE', 'Akun Tidak Aktif'), ('FAILED_CAPTCHA', 'CAPTCHA Salah'), ('LOCKED_OUT', 'Akun Dikunci')], max_length=30, verbose_name='Status')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('waktu', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Percobaan Login',
                'verbose_name_plural': 'Percobaan Login',
                'db_table': 'login_attempt',
                'ordering': ['-waktu'],
                'indexes': [models.Index(fields=['-waktu'], name='login_attem_waktu_74e616_idx'), models.Index(fields=['ip_address', '-waktu'], name='login_attem_ip_addr_7b5636_idx'), models.Index(fields=['username_attempted', '-waktu'], name='login_attem_usernam_c8636d_idx')],
            },
        ),
    ]
