# Generated by Django 6.0.4 on 2026-04-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_devicesession_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeuser',
            name='fakultas_id',
            field=models.CharField(blank=True, help_text='Link ke master.fakultas.kode_fakultas (varchar cross-schema)', max_length=10, null=True, verbose_name='Fakultas (Kode)'),
        ),
        migrations.AlterField(
            model_name='scopeuser',
            name='prodi_id',
            field=models.CharField(blank=True, help_text='Link ke master.program_studi.kode_prodi (varchar cross-schema)', max_length=10, null=True, verbose_name='Prodi (Kode)'),
        ),
    ]
