# Generated by Django 6.0.4 on 2026-04-23 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_scopeuser_fakultas_id_alter_scopeuser_prodi_id'),
        ('dokumen', '0003_verifikasidokumen_verifikasilog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('VERIF_APPROVED', 'Dokumen Disetujui'), ('VERIF_REJECTED', 'Dokumen Ditolak'), ('VERIF_NEED_REVISION', 'Dokumen Perlu Revisi'), ('VERIF_RESET', 'Verifikasi Di-reset'), ('SISTEM', 'Pemberitahuan Sistem')], db_index=True, default='SISTEM', max_length=30)),
                ('judul', models.CharField(max_length=200, verbose_name='Judul')),
                ('pesan', models.TextField(blank=True, default='', verbose_name='Pesan')),
                ('url_action', models.CharField(blank=True, default='', help_text='URL target saat notifikasi di-klik', max_length=500, verbose_name='URL Aksi')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sudah_dibaca', models.BooleanField(db_index=True, default=False, verbose_name='Sudah Dibaca')),
                ('tanggal_dibaca', models.DateTimeField(blank=True, null=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifikasi_dibuat', to=settings.AUTH_USER_MODEL, verbose_name='Pemicu')),
                ('dokumen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi_terkait', to='dokumen.dokumen')),
                ('penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi_diterima', to=settings.AUTH_USER_MODEL, verbose_name='Penerima')),
                ('verifikasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi_terkait', to='dokumen.verifikasidokumen')),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'db_table': 'notifikasi',
                'ordering': ['-tanggal_dibuat'],
                'indexes': [models.Index(fields=['penerima', '-tanggal_dibuat'], name='notifikasi_penerim_714518_idx'), models.Index(fields=['penerima', 'sudah_dibaca'], name='notifikasi_penerim_cf1c3d_idx')],
            },
        ),
    ]
