# Generated by Django 6.0.4 on 2026-04-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notifikasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_institusi', models.CharField(default='Universitas Ichsan Gorontalo', max_length=200)),
                ('nama_singkat', models.CharField(default='UNISAN', max_length=50)),
                ('tagline', models.CharField(default='Sistem Informasi Arsip Akreditasi', max_length=200)),
                ('tahun_berdiri', models.IntegerField(blank=True, null=True)),
                ('deskripsi_singkat', models.TextField(blank=True)),
                ('visi', models.TextField(blank=True)),
                ('misi', models.TextField(blank=True)),
                ('alamat', models.TextField(blank=True)),
                ('telepon', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil Institusi',
                'verbose_name_plural': 'Profil Institusi',
            },
        ),
    ]
