# Generated by Django 6.0.4 on 2026-04-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakultasTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_fakultas', models.CharField(help_text='Kode fakultas (sync dengan SIMDA master.fakultas.kode_fakultas). Contoh: FE, FH, FT', max_length=10, unique=True)),
                ('nama_fakultas', models.CharField(blank=True, help_text='Nama fakultas (cached dari SIMDA untuk display cepat)', max_length=200)),
                ('warna_primary', models.CharField(default='#2563EB', help_text='Hex color utama, dipakai untuk border-top, icon, arrow. Contoh: #059669', max_length=7)),
                ('warna_light', models.CharField(default='#DBEAFE', help_text='Hex color terang, dipakai untuk background tint kartu. Contoh: #D1FAE5', max_length=7)),
                ('icon_nama', models.CharField(blank=True, default='graduation-cap', help_text='Nama icon Lucide (opsional, default graduation-cap)', max_length=50)),
                ('urutan', models.IntegerField(default=0, help_text='Urutan tampil di UI (lower = first). Biasanya ikut urutan SIMDA.')),
                ('aktif', models.BooleanField(default=True, help_text='Nonaktifkan untuk sembunyikan dari UI tanpa delete')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme Fakultas',
                'verbose_name_plural': 'Theme Fakultas',
                'ordering': ['urutan', 'kode_fakultas'],
            },
        ),
    ]
