# Generated by Django 6.0.4 on 2026-04-24 10:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fakultastheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakultasProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_fakultas', models.CharField(help_text='Kode fakultas sync dengan SIMDA master.fakultas.kode_fakultas (FE, FH, FS, FK, FP, FT, S2)', max_length=10, unique=True)),
                ('nama_dekan', models.CharField(blank=True, help_text='Nama lengkap dekan dengan gelar (e.g. Dr. H. Budi Santoso, M.Si.)', max_length=200)),
                ('foto_dekan', models.ImageField(blank=True, help_text='Foto close-up dekan, ratio 1:1 atau 3:4 (min 400x400px)', null=True, upload_to=core.models._foto_dekan_path)),
                ('periode_dekan', models.CharField(blank=True, help_text='Periode jabatan (e.g. 2023-2027)', max_length=50)),
                ('visi', models.TextField(blank=True, help_text='Visi fakultas. Kalau kosong, fallback ke SIMDA.')),
                ('misi', models.TextField(blank=True, help_text='Misi fakultas (bisa multi-line, 1 baris per poin).')),
                ('tujuan', models.TextField(blank=True, help_text='Tujuan fakultas (opsional).')),
                ('aktif', models.BooleanField(default=True)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile Fakultas',
                'verbose_name_plural': 'Profile Fakultas',
                'ordering': ['kode_fakultas'],
            },
        ),
        migrations.CreateModel(
            name='ProdiProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(help_text='Kode prodi sync dengan SIMDA master.program_studi.kode_prodi', max_length=10, unique=True)),
                ('nama_kaprodi', models.CharField(blank=True, help_text='Nama lengkap ketua program studi dengan gelar', max_length=200)),
                ('foto_kaprodi', models.ImageField(blank=True, help_text='Foto close-up kaprodi, ratio 1:1 atau 3:4 (min 400x400px)', null=True, upload_to=core.models._foto_kaprodi_path)),
                ('periode_kaprodi', models.CharField(blank=True, help_text='Periode jabatan (e.g. 2024-2028)', max_length=50)),
                ('visi', models.TextField(blank=True, help_text='Visi prodi')),
                ('misi', models.TextField(blank=True, help_text='Misi prodi (1 baris per poin)')),
                ('tujuan', models.TextField(blank=True, help_text='Tujuan prodi (opsional)')),
                ('profil_lulusan', models.TextField(blank=True, help_text='Profil lulusan / kompetensi utama (opsional)')),
                ('aktif', models.BooleanField(default=True)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile Prodi',
                'verbose_name_plural': 'Profile Prodi',
                'ordering': ['kode_prodi'],
            },
        ),
    ]
