# Generated by Django 6.0.4 on 2026-04-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fakultasprofile_prodiprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='foto_rektor',
            field=models.ImageField(blank=True, help_text='Foto close-up Rektor', null=True, upload_to='profile/institusi/'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='kata_sambutan',
            field=models.TextField(blank=True, help_text='Kata sambutan Rektor untuk publik'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='nama_rektor',
            field=models.CharField(blank=True, help_text='Nama lengkap Rektor dengan gelar', max_length=200),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='periode_rektor',
            field=models.CharField(blank=True, help_text='Periode jabatan (e.g. 2023-2027)', max_length=50),
        ),
    ]
