# Generated by Django 6.0.4 on 2026-04-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_siteprofile_foto_rektor_siteprofile_kata_sambutan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='linkedin',
            field=models.URLField(blank=True, help_text='URL LinkedIn', max_length=500),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='telegram',
            field=models.URLField(blank=True, help_text='URL Telegram', max_length=500),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='tiktok',
            field=models.URLField(blank=True, help_text='URL TikTok', max_length=500),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='twitter_x',
            field=models.URLField(blank=True, help_text='URL Twitter / X', max_length=500, verbose_name='Twitter / X'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='whatsapp_channel',
            field=models.URLField(blank=True, help_text='URL WhatsApp Channel', max_length=500, verbose_name='WhatsApp Channel'),
        ),
    ]
