# Generated by Django 6.0.4 on 2026-04-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_siteprofile_linkedin_siteprofile_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='akreditasi_berlaku_sampai',
            field=models.DateField(blank=True, help_text='Berlaku sampai tanggal', null=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='akreditasi_lembaga',
            field=models.CharField(blank=True, default='BAN-PT', help_text='Lembaga pemberi akreditasi', max_length=50),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='akreditasi_no_sk',
            field=models.CharField(blank=True, help_text='Nomor SK akreditasi institusi', max_length=100),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='akreditasi_peringkat',
            field=models.CharField(blank=True, help_text="e.g. 'Unggul', 'Baik Sekali', 'B'", max_length=30),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='akreditasi_tanggal_sk',
            field=models.DateField(blank=True, help_text='Tanggal SK akreditasi', null=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='tujuan',
            field=models.TextField(blank=True, help_text='Tujuan universitas (1 poin per baris)'),
        ),
    ]
