# Generated by Django 6.0.4 on 2026-04-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_siteprofile_akreditasi_berlaku_sampai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveiVMTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('mahasiswa', 'Mahasiswa'), ('dosen', 'Dosen'), ('tendik', 'Tenaga Kependidikan'), ('alumni', 'Alumni')], max_length=20)),
                ('prodi', models.CharField(max_length=150)),
                ('angkatan', models.CharField(blank=True, max_length=10, null=True)),
                ('skor_v', models.FloatField(verbose_name='Skor Visi')),
                ('skor_m', models.FloatField(verbose_name='Skor Misi')),
                ('skor_t', models.FloatField(verbose_name='Skor Tujuan')),
                ('skor_s', models.FloatField(verbose_name='Skor Sasaran')),
                ('skor_total', models.FloatField(verbose_name='Skor Rata-rata VMTS')),
                ('media_sosialisasi', models.CharField(blank=True, max_length=300, null=True)),
                ('masukan', models.TextField(blank=True, null=True)),
                ('saran', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Respons Survei VMTS',
                'verbose_name_plural': 'Respons Survei VMTS',
                'ordering': ['-created_at'],
            },
        ),
    ]
