# Generated by Django 6.0.4 on 2026-04-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_surveivmts'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='survei_vmts_aktif',
            field=models.BooleanField(default=True, verbose_name='Survei VMTS Aktif'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='survei_vmts_tahun_akademik',
            field=models.CharField(default='2024/2025', help_text='Contoh: 2024/2025', max_length=20, verbose_name='Tahun Akademik Survei VMTS'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='survei_vmts_target',
            field=models.PositiveIntegerField(default=300, verbose_name='Target Responden Survei VMTS'),
        ),
    ]
