# Generated by Django 6.0.4 on 2026-04-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_siteprofile_survei_vmts_aktif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodiprofile',
            name='target_survei_alumni',
            field=models.PositiveIntegerField(default=2, verbose_name='Target Alumni'),
        ),
        migrations.AddField(
            model_name='prodiprofile',
            name='target_survei_dosen',
            field=models.PositiveIntegerField(default=5, verbose_name='Target Dosen'),
        ),
        migrations.AddField(
            model_name='prodiprofile',
            name='target_survei_mahasiswa',
            field=models.PositiveIntegerField(default=20, verbose_name='Target Mahasiswa'),
        ),
        migrations.AddField(
            model_name='prodiprofile',
            name='target_survei_tendik',
            field=models.PositiveIntegerField(default=3, verbose_name='Target Tendik'),
        ),
        migrations.AddField(
            model_name='prodiprofile',
            name='target_survei_total',
            field=models.PositiveIntegerField(default=30, help_text='Total target responden survei VMTS untuk prodi ini', verbose_name='Target Total Responden Survei'),
        ),
    ]
