# Generated by Django 6.0.4 on 2026-10-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_prodiprofile_target_survei_alumni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakultasprofile',
            name='sasaran',
            field=models.TextField(blank=True, help_text='Sasaran (1 poin per baris). Diambil dari SIMDA.'),
        ),
        migrations.AddField(
            model_name='fakultasprofile',
            name='vmts_simda_at',
            field=models.DateTimeField(blank=True, help_text='Waktu VMTS terakhir disinkron dari SIMDA (Pusat Sinkronisasi). Isian VMTS akan ditimpa sinkron bila SIMDA punya isinya.', null=True, verbose_name='VMTS dari SIMDA terakhir'),
        ),
        migrations.AddField(
            model_name='prodiprofile',
            name='sasaran',
            field=models.TextField(blank=True, help_text='Sasaran (1 poin per baris). Diambil dari SIMDA.'),
        ),
        migrations.AddField(
            model_name='prodiprofile',
            name='vmts_simda_at',
            field=models.DateTimeField(blank=True, help_text='Waktu VMTS terakhir disinkron dari SIMDA (Pusat Sinkronisasi). Isian VMTS akan ditimpa sinkron bila SIMDA punya isinya.', null=True, verbose_name='VMTS dari SIMDA terakhir'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='sasaran',
            field=models.TextField(blank=True, help_text='Sasaran (1 poin per baris). Diambil dari SIMDA.'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='vmts_simda_at',
            field=models.DateTimeField(blank=True, help_text='Waktu VMTS terakhir disinkron dari SIMDA (Pusat Sinkronisasi). Isian VMTS akan ditimpa sinkron bila SIMDA punya isinya.', null=True, verbose_name='VMTS dari SIMDA terakhir'),
        ),
    ]
