# Generated by Django 6.0.4 on 2026-04-23 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_akreditasi', '0003_importlog_importlogitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesiAkreditasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(help_text='Contoh: Re-akreditasi T21 LAM Teknik 2026', max_length=300, verbose_name='Judul Sesi')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('kode_prodi', models.CharField(help_text='Pointer ke master.program_studi.kode_prodi', max_length=10, verbose_name='Kode Prodi')),
                ('nama_prodi_snapshot', models.CharField(blank=True, max_length=200, verbose_name='Nama Prodi (snapshot)')),
                ('kode_fakultas', models.CharField(blank=True, max_length=10, verbose_name='Kode Fakultas')),
                ('tipe', models.CharField(choices=[('AKREDITASI_BARU', 'Akreditasi Baru (Pertama Kali)'), ('REAKREDITASI', 'Re-akreditasi (Perpanjangan)'), ('AKREDITASI_KHUSUS', 'Akreditasi Khusus / Lainnya')], default='REAKREDITASI', max_length=20, verbose_name='Tipe Akreditasi')),
                ('tahun_akademik', models.CharField(help_text='Contoh: 2025/2026', max_length=20, verbose_name='Tahun Akademik Sesi')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai Sesi')),
                ('tanggal_target_selesai', models.DateField(verbose_name='Target Selesai')),
                ('deadline_upload_dokumen', models.DateField(blank=True, null=True, verbose_name='Deadline Upload Dokumen Wajib')),
                ('tanggal_submit', models.DateField(blank=True, null=True, verbose_name='Tanggal Submit ke LAM/BAN-PT')),
                ('tanggal_visitasi_mulai', models.DateField(blank=True, null=True, verbose_name='Tanggal Visitasi Mulai')),
                ('tanggal_visitasi_selesai', models.DateField(blank=True, null=True, verbose_name='Tanggal Visitasi Selesai')),
                ('tanggal_sertifikat', models.DateField(blank=True, null=True, verbose_name='Tanggal Sertifikat Terbit')),
                ('status', models.CharField(choices=[('PERSIAPAN', 'Persiapan Dokumen'), ('REVIEW_INTERNAL', 'Review Internal'), ('SUBMITTED', 'Sudah Submit ke LAM/BAN-PT'), ('VISITASI_AKTIF', 'Visitasi Berlangsung'), ('MENUNGGU_HASIL', 'Menunggu Hasil'), ('SELESAI', 'Selesai (Sertifikat Terbit)'), ('DIBATALKAN', 'Dibatalkan')], default='PERSIAPAN', max_length=20, verbose_name='Status')),
                ('nilai_akhir', models.CharField(blank=True, help_text='Contoh: A, B, Baik Sekali, Unggul, dll', max_length=20, verbose_name='Nilai Akreditasi Akhir')),
                ('nomor_sk_akreditasi', models.CharField(blank=True, max_length=100, verbose_name='Nomor SK Akreditasi')),
                ('berlaku_sampai', models.DateField(blank=True, null=True, verbose_name='Berlaku Sampai')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesi_dibuat', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('instrumen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesi_akreditasi', to='master_akreditasi.instrumen', verbose_name='Instrumen')),
                ('terakhir_diupdate_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesi_diupdate', to=settings.AUTH_USER_MODEL, verbose_name='Terakhir Diupdate Oleh')),
            ],
            options={
                'verbose_name': 'Sesi Akreditasi',
                'verbose_name_plural': 'Sesi Akreditasi',
                'db_table': 'sesi_akreditasi',
                'ordering': ['-tanggal_mulai', '-tanggal_dibuat'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneSesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Milestone')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('tanggal_target', models.DateField(verbose_name='Tanggal Target')),
                ('tanggal_aktual', models.DateField(blank=True, null=True, verbose_name='Tanggal Aktual')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('status', models.CharField(choices=[('BELUM', 'Belum Dimulai'), ('PROGRESS', 'Sedang Berjalan'), ('SELESAI', 'Selesai'), ('TERLEWAT', 'Terlewat / Tertunda')], default='BELUM', max_length=15, verbose_name='Status')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='sesi.sesiakreditasi')),
            ],
            options={
                'verbose_name': 'Milestone Sesi',
                'verbose_name_plural': 'Milestones Sesi',
                'db_table': 'milestone_sesi',
                'ordering': ['urutan', 'tanggal_target'],
            },
        ),
        migrations.CreateModel(
            name='CatatanSesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('UMUM', 'Catatan Umum'), ('REVIEW', 'Catatan Review'), ('VISITASI', 'Catatan Visitasi'), ('ASESOR', 'Komentar Asesor'), ('INTERNAL', 'Catatan Internal LP3M')], default='UMUM', max_length=15, verbose_name='Tipe Catatan')),
                ('isi', models.TextField(verbose_name='Isi Catatan')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catatan_sesi_dibuat', to=settings.AUTH_USER_MODEL)),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan', to='sesi.sesiakreditasi')),
            ],
            options={
                'verbose_name': 'Catatan Sesi',
                'verbose_name_plural': 'Catatan Sesi',
                'db_table': 'catatan_sesi',
                'ordering': ['-tanggal_dibuat'],
            },
        ),
        migrations.AddConstraint(
            model_name='sesiakreditasi',
            constraint=models.UniqueConstraint(fields=('instrumen', 'kode_prodi', 'tahun_akademik'), name='unique_sesi_per_prodi_instrumen_tahun'),
        ),
    ]
