# Generated by Django 6.0.4 on 2026-04-23 02:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_akreditasi', '0003_importlog_importlogitem'),
        ('sesi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sesiakreditasi',
            name='unique_sesi_per_prodi_instrumen_tahun',
        ),
        migrations.AddField(
            model_name='sesiakreditasi',
            name='jumlah_tahun_evaluasi',
            field=models.PositiveSmallIntegerField(default=3, help_text='3 untuk LAM, 4 untuk BAN-PT IAPS 4.0', verbose_name='Jumlah Tahun Evaluasi'),
        ),
        migrations.AddField(
            model_name='sesiakreditasi',
            name='tahun_ts',
            field=models.CharField(default='2025/2026', help_text='Tahun akademik saat submit akreditasi. Contoh: 2025/2026', max_length=20, verbose_name='Tahun TS (Saat Ini)'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='sesiakreditasi',
            constraint=models.UniqueConstraint(fields=('instrumen', 'kode_prodi', 'tahun_ts'), name='unique_sesi_per_prodi_instrumen_tahun_ts'),
        ),
        migrations.RemoveField(
            model_name='sesiakreditasi',
            name='tahun_akademik',
        ),
    ]
