# Generated by Django 6.0.4 on 2026-04-23 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_akreditasi', '0003_importlog_importlogitem'),
        ('sesi', '0002_remove_sesiakreditasi_unique_sesi_per_prodi_instrumen_tahun_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesiakreditasi',
            name='dibuat_oleh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesi_dibuat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sesiakreditasi',
            name='instrumen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesi_akreditasi', to='master_akreditasi.instrumen'),
        ),
        migrations.AlterField(
            model_name='sesiakreditasi',
            name='judul',
            field=models.CharField(max_length=300, verbose_name='Judul Sesi'),
        ),
        migrations.AlterField(
            model_name='sesiakreditasi',
            name='kode_prodi',
            field=models.CharField(max_length=10, verbose_name='Kode Prodi'),
        ),
        migrations.AlterField(
            model_name='sesiakreditasi',
            name='nilai_akhir',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nilai Akreditasi Akhir'),
        ),
        migrations.AlterField(
            model_name='sesiakreditasi',
            name='tanggal_submit',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Submit'),
        ),
        migrations.AlterField(
            model_name='sesiakreditasi',
            name='terakhir_diupdate_oleh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesi_diupdate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BundleShareToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token')),
                ('label', models.CharField(help_text="Nama atau keperluan token, misal: 'Asesor LAMEMBA Dr. Budi' atau 'Submission BAN-PT'", max_length=200, verbose_name='Label / Keperluan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Kosongkan untuk tanpa expired. Disarankan diisi untuk keamanan.', null=True, verbose_name='Kadaluarsa Pada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terakhir Diakses')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Akses')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_tokens_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_tokens', to='sesi.sesiakreditasi', verbose_name='Sesi Akreditasi')),
            ],
            options={
                'verbose_name': 'Token Share Bundle',
                'verbose_name_plural': 'Token Share Bundle',
                'db_table': 'bundle_share_token',
                'ordering': ['-created_at'],
            },
        ),
    ]
