# Generated by Django 6.0.4 on 2026-04-22 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Kode singkat, contoh: IAPS40, LAMTEKNIK, LAMINFOKOM', max_length=30, unique=True, verbose_name='Kode Instrumen')),
                ('nama_resmi', models.CharField(help_text='Nama lengkap instrumen, contoh: BAN-PT IAPS 4.0', max_length=200, verbose_name='Nama Resmi')),
                ('nama_singkat', models.CharField(help_text='Contoh: IAPS 4.0, LAM Teknik', max_length=50, verbose_name='Nama Singkat')),
                ('versi', models.CharField(blank=True, help_text='Contoh: 4.0, 2.0, 2024', max_length=20, verbose_name='Versi')),
                ('lembaga', models.CharField(help_text='Contoh: BAN-PT, LAM Teknik, LAMSPAK', max_length=150, verbose_name='Lembaga Penyelenggara')),
                ('label_standar', models.CharField(default='Kriteria', help_text="Contoh: 'Kriteria' (BAN-PT) atau 'Standar' (LAM lain)", max_length=50, verbose_name='Label untuk Standar')),
                ('label_substandar', models.CharField(default='Sub-Kriteria', help_text="Contoh: 'Sub-Kriteria', 'Indikator', 'Butir'", max_length=50, verbose_name='Label untuk Sub-Standar')),
                ('label_butir', models.CharField(default='Butir Dokumen', help_text="Contoh: 'Butir Dokumen', 'Item'", max_length=50, verbose_name='Label untuk Butir Dokumen')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('tahun_berlaku', models.CharField(blank=True, help_text='Contoh: 2018-sekarang, 2024-sekarang', max_length=20, verbose_name='Tahun Berlaku')),
                ('url_referensi', models.URLField(blank=True, help_text='Link ke halaman resmi instrumen', verbose_name='URL Referensi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='instrumen/logo/', verbose_name='Logo Lembaga')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan Tampil')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instrumen Akreditasi',
                'verbose_name_plural': 'Instrumen Akreditasi',
                'db_table': 'instrumen',
                'ordering': ['urutan', 'kode'],
            },
        ),
        migrations.CreateModel(
            name='MappingProdiInstrumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodi_id', models.BigIntegerField(help_text='Link ke master.program_studi.id', unique=True, verbose_name='ID Program Studi')),
                ('kode_prodi', models.CharField(help_text='Kode prodi dari SIMDA, untuk display. Contoh: T21, E11', max_length=20, verbose_name='Kode Prodi')),
                ('nama_prodi', models.CharField(help_text='Cached dari SIMDA untuk display cepat', max_length=200, verbose_name='Nama Prodi')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
                ('instrumen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prodi_terdaftar', to='master_akreditasi.instrumen', verbose_name='Instrumen Akreditasi')),
            ],
            options={
                'verbose_name': 'Mapping Prodi ↔ Instrumen',
                'verbose_name_plural': 'Mapping Prodi ↔ Instrumen',
                'db_table': 'mapping_prodi_instrumen',
                'ordering': ['kode_prodi'],
            },
        ),
        migrations.CreateModel(
            name='Standar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(help_text='Contoh: 1, 2, A, B, I, II', max_length=20, verbose_name='Nomor Standar')),
                ('nama', models.CharField(help_text="Contoh: 'Visi, Misi, Tujuan, dan Strategi'", max_length=300, verbose_name='Nama Standar')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('bobot', models.DecimalField(blank=True, decimal_places=2, help_text='Persentase bobot standar dari total, contoh: 11.11', max_digits=5, null=True, verbose_name='Bobot Nilai (%)')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
                ('instrumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standar', to='master_akreditasi.instrumen', verbose_name='Instrumen')),
            ],
            options={
                'verbose_name': 'Standar / Kriteria',
                'verbose_name_plural': 'Standar / Kriteria',
                'db_table': 'standar',
                'ordering': ['instrumen', 'urutan', 'nomor'],
            },
        ),
        migrations.CreateModel(
            name='SubStandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(help_text='Contoh: 2.1, 2.1.1, 2.1.1.a', max_length=30, verbose_name='Nomor')),
                ('nama', models.CharField(help_text="Contoh: 'Sistem Tata Pamong'", max_length=300, verbose_name='Nama Sub-Standar')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('panduan', models.TextField(blank=True, help_text='Panduan untuk asesor/tim akreditasi', verbose_name='Panduan Penilaian')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Kosongkan jika level paling atas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master_akreditasi.substandar', verbose_name='Sub-Standar Induk')),
                ('standar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_standar', to='master_akreditasi.standar', verbose_name='Standar Induk')),
            ],
            options={
                'verbose_name': 'Sub-Standar',
                'verbose_name_plural': 'Sub-Standar',
                'db_table': 'sub_standar',
                'ordering': ['standar', 'urutan', 'nomor'],
            },
        ),
        migrations.CreateModel(
            name='ButirDokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Kode unik, contoh: 2.1.1-A', max_length=50, verbose_name='Kode Butir')),
                ('nama_dokumen', models.CharField(help_text="Contoh: 'SK Senat Akademik tentang Tata Pamong'", max_length=300, verbose_name='Nama Dokumen')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('panduan_dokumen', models.TextField(blank=True, help_text='Hal-hal yang wajib ada di dalam dokumen', verbose_name='Panduan Isi Dokumen')),
                ('kategori_kepemilikan', models.CharField(choices=[('UNIVERSITAS', 'Universitas'), ('BIRO', 'Biro / Lembaga'), ('FAKULTAS', 'Fakultas'), ('PRODI', 'Program Studi')], help_text='Menentukan siapa yang bertanggung jawab mengunggah', max_length=15, verbose_name='Kategori Kepemilikan')),
                ('wajib', models.BooleanField(default=True, help_text='Jika True, dokumen ini wajib diunggah untuk akreditasi', verbose_name='Wajib')),
                ('format_diterima', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'Word (DOCX)'), ('XLSX', 'Excel (XLSX)'), ('PPTX', 'PowerPoint (PPTX)'), ('GAMBAR', 'Gambar (JPG/PNG)'), ('APAPUN', 'Format Apapun')], default='PDF', max_length=15, verbose_name='Format File')),
                ('ukuran_max_mb', models.PositiveIntegerField(default=50, verbose_name='Ukuran Maks (MB)')),
                ('status_akses_default', models.CharField(choices=[('TERBUKA', 'Terbuka'), ('INTERNAL', 'Internal')], default='INTERNAL', help_text='Default saat upload. User bisa override (dengan hak akses).', max_length=10, verbose_name='Status Akses Default')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
                ('sub_standar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='butir_dokumen', to='master_akreditasi.substandar', verbose_name='Sub-Standar')),
            ],
            options={
                'verbose_name': 'Butir Dokumen',
                'verbose_name_plural': 'Butir Dokumen',
                'db_table': 'butir_dokumen',
                'ordering': ['sub_standar', 'urutan', 'kode'],
            },
        ),
        migrations.AddConstraint(
            model_name='standar',
            constraint=models.UniqueConstraint(fields=('instrumen', 'nomor'), name='unique_instrumen_standar_nomor'),
        ),
        migrations.AddConstraint(
            model_name='substandar',
            constraint=models.UniqueConstraint(fields=('standar', 'nomor'), name='unique_standar_substandar_nomor'),
        ),
        migrations.AddConstraint(
            model_name='butirdokumen',
            constraint=models.UniqueConstraint(fields=('sub_standar', 'kode'), name='unique_substandar_butir_kode'),
        ),
    ]
