# Generated by Django 6.0.4 on 2026-04-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_akreditasi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingprodiinstrumen',
            name='prodi_id',
        ),
        migrations.AlterField(
            model_name='mappingprodiinstrumen',
            name='kode_prodi',
            field=models.CharField(help_text='Link ke master.program_studi.kode_prodi (PK)', max_length=10, unique=True, verbose_name='Kode Prodi'),
        ),
    ]
