# Generated by Django 6.0.4 on 2026-04-22 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_akreditasi', '0002_remove_mappingprodiinstrumen_prodi_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nama File')),
                ('file_size_kb', models.PositiveIntegerField(default=0, verbose_name='Ukuran (KB)')),
                ('file', models.FileField(blank=True, null=True, upload_to='import_master/%Y/%m/', verbose_name='File Excel')),
                ('mode', models.CharField(choices=[('UPDATE', 'Update jika sudah ada'), ('SKIP', 'Skip jika sudah ada'), ('ERROR', 'Error jika sudah ada')], default='UPDATE', max_length=10, verbose_name='Mode Import')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Total Baris')),
                ('valid_rows', models.PositiveIntegerField(default=0, verbose_name='Baris Valid')),
                ('error_rows', models.PositiveIntegerField(default=0, verbose_name='Baris Error')),
                ('substandar_created', models.PositiveIntegerField(default=0)),
                ('substandar_updated', models.PositiveIntegerField(default=0)),
                ('butir_created', models.PositiveIntegerField(default=0)),
                ('butir_updated', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Preview'), ('PREVIEWED', 'Preview Ditampilkan'), ('COMMITTED', 'Tersimpan ke Database'), ('CANCELLED', 'Dibatalkan'), ('FAILED', 'Gagal')], default='PENDING', max_length=15, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Pesan Error')),
                ('waktu_upload', models.DateTimeField(auto_now_add=True)),
                ('waktu_commit', models.DateTimeField(blank=True, null=True)),
                ('instrumen', models.ForeignKey(help_text='Data akan di-import ke instrumen ini', on_delete=django.db.models.deletion.PROTECT, related_name='import_logs', to='master_akreditasi.instrumen', verbose_name='Instrumen Target')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_imports', to=settings.AUTH_USER_MODEL, verbose_name='Uploader')),
            ],
            options={
                'verbose_name': 'Log Import Excel',
                'verbose_name_plural': 'Log Import Excel',
                'db_table': 'import_log',
                'ordering': ['-waktu_upload'],
            },
        ),
        migrations.CreateModel(
            name='ImportLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.CharField(choices=[('SUBSTANDAR', 'Sub-Standar'), ('BUTIR', 'Butir Dokumen')], max_length=15, verbose_name='Sheet Asal')),
                ('row_number', models.PositiveIntegerField(verbose_name='Nomor Baris')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Data Baris')),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Tidak Valid'), ('DUPLICATE', 'Duplikat (akan di-skip)'), ('WILL_UPDATE', 'Akan di-update'), ('WILL_CREATE', 'Akan dibuat baru'), ('CREATED', 'Berhasil dibuat'), ('UPDATED', 'Berhasil di-update'), ('SKIPPED', 'Dilewati'), ('FAILED', 'Gagal')], max_length=15, verbose_name='Status Item')),
                ('error_detail', models.TextField(blank=True, verbose_name='Detail Error')),
                ('butir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='master_akreditasi.butirdokumen')),
                ('import_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='master_akreditasi.importlog')),
                ('substandar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='master_akreditasi.substandar')),
            ],
            options={
                'verbose_name': 'Item Import',
                'verbose_name_plural': 'Item Import',
                'db_table': 'import_log_item',
                'ordering': ['import_log', 'sheet', 'row_number'],
            },
        ),
    ]
