# Generated by Django 6.0.4 on 2026-10-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_akreditasi', '0004_datadosenref_fakultasref_jabatanfungsionalref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='butirdokumen',
            name='kode_bersama',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Butir dengan kode yang sama (lintas instrumen) memakai dokumen yang sama: cukup diunggah sekali. Contoh: UNIV-KEBIJAKAN-SPMI. Kosongkan jika tidak dibagi.', max_length=60, verbose_name='Kode Dokumen Bersama'),
        ),
    ]
