# Generated by Django 6.0.4 on 2026-10-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_akreditasi', '0006_mapping_jenis_serdos_sk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butirdatadosenmapping',
            name='jenis_data',
            field=models.CharField(choices=[('BKD', 'Beban Kerja Dosen'), ('JABFUNG', 'Riwayat Jabatan Fungsional'), ('PENDIDIKAN', 'Riwayat Pendidikan'), ('PROFIL', 'Profil Dosen (Identitas + ID Akademik)'), ('SERDOS', 'Sertifikat Pendidik (Serdos)'), ('SK_PENGANGKATAN', 'SK Pengangkatan Dosen Tetap'), ('ID_AKADEMIK', 'Profil & ID Akademik (SINTA, Google Scholar, Scopus, ORCID, Garuda)')], max_length=20, verbose_name='Jenis Data SIMDA'),
        ),
        migrations.AlterField(
            model_name='snapshotdatasimda',
            name='jenis_data',
            field=models.CharField(choices=[('BKD', 'Beban Kerja Dosen'), ('JABFUNG', 'Riwayat Jabatan Fungsional'), ('PENDIDIKAN', 'Riwayat Pendidikan'), ('PROFIL', 'Profil Dosen (Identitas + ID Akademik)'), ('SERDOS', 'Sertifikat Pendidik (Serdos)'), ('SK_PENGANGKATAN', 'SK Pengangkatan Dosen Tetap'), ('ID_AKADEMIK', 'Profil & ID Akademik (SINTA, Google Scholar, Scopus, ORCID, Garuda)'), ('DAFTAR_DTPS', 'Daftar DTPS Sesi (snapshot lengkap pool dosen)')], max_length=20),
        ),
    ]
