# Generated by Django 6.0.4 on 2026-10-04 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_akreditasi', '0007_mapping_jenis_id_akademik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dtpsdosensesi',
            name='catatan_sinkron',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Catatan Sinkron'),
        ),
        migrations.AddField(
            model_name='dtpsdosensesi',
            name='perlu_ditinjau',
            field=models.BooleanField(default=False, help_text='Diisi sinkron: dosen auto-homebase yang di SIMDA tidak lagi homebase prodi ini atau tidak aktif. Admin yang memutuskan menonaktifkan.', verbose_name='Perlu Ditinjau'),
        ),
        migrations.AddField(
            model_name='mappingprodiinstrumen',
            name='portal_fakultas_slug',
            field=models.CharField(blank=True, default='', help_text='Contoh: fisip (dari portal.unisan.ac.id/fakultas/<slug>/).', max_length=50, verbose_name='Slug Portal Fakultas'),
        ),
        migrations.AddField(
            model_name='mappingprodiinstrumen',
            name='portal_slug',
            field=models.CharField(blank=True, default='', help_text='Contoh: ilmu-pemerintahan (dari portal.unisan.ac.id/prodi/<slug>/). Kosong = tanpa tautan portal.', max_length=100, verbose_name='Slug Portal Prodi'),
        ),
        migrations.CreateModel(
            name='SinkronLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('RPS', 'RPS SI-OBE'), ('DTPS', 'DTPS & Data Dosen SIMDA'), ('TAUTAN', 'Tautan Aplikasi & Portal'), ('CACHE', 'Bersihkan Cache'), ('SEMUA', 'Sinkron Semua')], max_length=10)),
                ('lingkup', models.CharField(blank=True, default='', help_text='Kosong = semua prodi; atau kode prodi (mis. S21) untuk sinkron per sesi.', max_length=20)),
                ('status', models.CharField(choices=[('ANTRI', 'Antri'), ('BERJALAN', 'Berjalan'), ('SUKSES', 'Sukses'), ('GAGAL', 'Gagal')], db_index=True, default='ANTRI', max_length=10)),
                ('sumber', models.CharField(default='TOMBOL', help_text='TOMBOL / CRON / CLI', max_length=10)),
                ('mulai', models.DateTimeField(auto_now_add=True)),
                ('selesai', models.DateTimeField(blank=True, null=True)),
                ('ringkasan', models.CharField(blank=True, default='', max_length=500)),
                ('output', models.TextField(blank=True, default='')),
                ('dipicu_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinkron_dipicu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Sinkronisasi',
                'verbose_name_plural': 'Log Sinkronisasi',
                'db_table': 'sinkron_log',
                'ordering': ['-mulai'],
            },
        ),
    ]
