# Generated by Django 6.0.4 on 2026-10-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_akreditasi', '0008_sinkron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinkronlog',
            name='jenis',
            field=models.CharField(choices=[('RPS', 'RPS SI-OBE'), ('DTPS', 'DTPS & Data Dosen SIMDA'), ('TAUTAN', 'Tautan Aplikasi & Portal'), ('VMTS', 'VMTS SIMDA'), ('CACHE', 'Bersihkan Cache'), ('SEMUA', 'Sinkron Semua')], max_length=10),
        ),
    ]
